### ISSUE TITLE
RuntimeError: log_vml_cpu not implemented for 'Long' while training DALLE

### ISSUE THREAD

**Issue by balag59** [lucidrains/DALLE-pytorch#102]
Hi,
Thank you so much for your work! I'm however getting the following runtime error while trying running train_dalle.py:
**RuntimeError: log_vml_cpu not implemented for 'Long'**

This happens irrespective of the VAE I specify(pretrained or otherwise). It is able to find the data of the matching image and text pairs but fails on the following line:
**for i, (text, images, mask) in enumerate(dl):**

Any ideas on what could be causing this issue? Any help would be greatly appreciated!

**Comment by lucidrains** [comment]
@balag59 hi Balaji! could you paste for me the full trace of the error?

**Comment by balag59** [comment]
Sure! Here you go:

Traceback (most recent call last):
  File "train_dalle.py", line 215, in <module>
    for i, (text, images, mask) in enumerate(dl):
  File "/home/ubuntu/anaconda3/envs/pytorch_latest_p37/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 435, in __next__
    data = self._next_data()
  File "/home/ubuntu/anaconda3/envs/pytorch_latest_p37/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 475, in _next_data
    data = self._dataset_fetcher.fetch(index)  # may raise StopIteration
  File "/home/ubuntu/anaconda3/envs/pytorch_latest_p37/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/ubuntu/anaconda3/envs/pytorch_latest_p37/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "train_dalle.py", line 173, in __getitem__
    image_tensor = self.image_tranform(image)
  File "/home/ubuntu/anaconda3/envs/pytorch_latest_p37/lib/python3.7/site-packages/torchvision/transforms/transforms.py", line 67, in __call__
    img = t(img)
  File "/home/ubuntu/anaconda3/envs/pytorch_latest_p37/lib/python3.7/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/ubuntu/anaconda3/envs/pytorch_latest_p37/lib/python3.7/site-packages/torchvision/transforms/transforms.py", line 823, in forward
    i, j, h, w = self.get_params(img, self.scale, self.ratio)
  File "/home/ubuntu/anaconda3/envs/pytorch_latest_p37/lib/python3.7/site-packages/torchvision/transforms/transforms.py", line 787, in get_params
    log_ratio = torch.log(torch.tensor(ratio))
RuntimeError: log_vml_cpu not implemented for 'Long'

Please let me know if you need anything else.Thanks!

**Comment by lucidrains** [comment]
@balag59 should be fixed in https://github.com/lucidrains/DALLE-pytorch/commit/ebf33f903e20d7c5677933fd6f5f044e103ff9d2 !

**Comment by balag59** [comment]
> @balag59 should be fixed in [ebf33f9](https://github.com/lucidrains/DALLE-pytorch/commit/ebf33f903e20d7c5677933fd6f5f044e103ff9d2) !

Thanks a ton! That fixed it!
