### ISSUE TITLE
Deepspeed Breaks Trying to Write to the Same Files

### ISSUE THREAD

**Issue by afiaka87** [lucidrains/DALLE-pytorch#141]
The current train_dalle.py will attempt to read/write to/from the same pretrained model checkpoints if they haven't been cached yet.
```bash
FileNotFoundError: [Errno 2] No such file or directory: '/root/.cache/dalle/tmp.encoder.pkl' -> '/root/.cache/dalle/encoder.pkl'
100%|████████████████████████| 215185363/215185363 [00:21<00:00, 9883569.70it/s]
Traceback (most recent call last):
  File "train_dalle.py", line 109, in <module>
    vae = vae_klass()
  File "/root/DALLE-pytorch/dalle_pytorch/vae.py", line 83, in __init__
    self.enc = load_model(download(OPENAI_VAE_ENCODER_PATH))
  File "/root/DALLE-pytorch/dalle_pytorch/vae.py", line 74, in download
    os.rename(download_target_tmp, download_target)
FileNotFoundError: [Errno 2] No such file or directory: '/root/.cache/dalle/tmp.encoder.pkl' -> '/root/.cache/dalle/encoder.pkl'
100%|████████████████████████| 215185363/215185363 [00:22<00:00, 9738539.45it/s]
Traceback (most recent call last):
  File "train_dalle.py", line 109, in <module>
    vae = vae_klass()
  File "/root/DALLE-pytorch/dalle_pytorch/vae.py", line 83, in __init__
    self.enc = load_model(download(OPENAI_VAE_ENCODER_PATH))
  File "/root/DALLE-pytorch/dalle_pytorch/vae.py", line 74, in download
    os.rename(download_target_tmp, download_target)
FileNotFoundError: [Errno 2] No such file or directory: '/root/.cache/dalle/tmp.encoder.pkl' -> '/root/.cache/dalle/encoder.pkl'
 88%|█████████████████████▏  | 189546496/215185363 [00:22<00:07, 3572270.67it/s]Killing subprocess 2749
Killing subprocess 2750
Killing subprocess 2751
Killing subprocess 2752
Killing subprocess 2753
Killing subprocess 2754
Killing subprocess 2756
Killing subprocess 2758
Traceback (most recent call last):
  File "/opt/conda/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/opt/conda/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/opt/conda/lib/python3.8/site-packages/deepspeed/launcher/launch.py", line 171, in <module>
    main()
  File "/opt/conda/lib/python3.8/site-packages/deepspeed/launcher/launch.py", line 161, in main
    sigkill_handler(signal.SIGTERM, None)  # not coming back
  File "/opt/conda/lib/python3.8/site-packages/deepspeed/launcher/launch.py", line 139, in sigkill_handler
    raise subprocess.CalledProcessError(returncode=last_return_code, cmd=cmd)
subprocess.CalledProcessError: Command '['/opt/conda/bin/python', '-u', 'train_dalle.py', '--local_rank=7', '--image_text_folder', '/root/output/', '--deepspeed']' returned non-zero exit status 1.
```

For now, to get it working, just run without deepspeed using python and cancel the program after the downloads are finished.

As for a long term solution - I assume deepspeed has a way to mark code as meant to run only once? Perhaps it could just be pinned to the GPU with 0 rank?

**Comment by mehdidc** [comment]
Yes it's how it's done in Horovod as well, I/O is done usually in rank zero, I saw there is an example of printing in rank zero in MegaTron: https://github.com/microsoft/DeepSpeedExamples/blob/28a32fb313479b0d18c0157b62945026a4fd4ef6/Megatron-LM/utils.py#L30, same is done for checkpointing: https://github.com/microsoft/DeepSpeedExamples/blob/28a32fb313479b0d18c0157b62945026a4fd4ef6/Megatron-LM/utils.py#L189

**Comment by janEbert** [comment]
It's all underway, give me just a few minutes to test whether everything works. :)

**Comment by afiaka87** [comment]
I've independently verified this is no longer a problem.
