### ISSUE TITLE
Horovod "NoneType" object has no attribute 'init'

### ISSUE THREAD

**Issue by afiaka87** [lucidrains/DALLE-pytorch#212]
```sh
[3]<stdout>:Using Horovod for distributed execution
[3]<stderr>:Traceback (most recent call last):
[3]<stderr>:  File "/workspace/horovod_stuff/dalle-pytorch/train_dalle.py", line 87, in <module>
[3]<stderr>:    distr_backend.initialize()
[3]<stderr>:  File "/workspace/horovod_stuff/dalle-pytorch/dalle_pytorch/distributed_backends/distributed_backend.py", line 68, in initialize
[3]<stderr>:    self._initialize()
[3]<stderr>:  File "/workspace/horovod_stuff/dalle-pytorch/dalle_pytorch/distributed_backends/horovod_backend.py", line 35, in _initialize
[3]<stderr>:    self.backend_module.init()
[3]<stderr>:AttributeError: 'NoneType' object has no attribute 'init'
```

Getting this error when attempting to run with:
```sh
PROJECT_PATH=/workspace/horovod_stuff/dalle-pytorch
PYTHON_PATH=/opt/conda/envs/dalle_env/bin/python
DATASET=/root/Datasets
NUM_GPUS=8
CONDA_ENV=dalle_env

cd $PROJECT_PATH
conda activate $CONDA_ENV

horovodrun -np $NUM_GPUS $PYTHON_PATH $PROJECT_PATH/train_dalle.py --taming --image_text_folder $DATASET --truncate_captions --distr_backend horovod
```

**Comment by afiaka87** [comment]
hm - @janEbert i'm getting this in main on JUWELS as well
