### ISSUE TITLE
Inference with DeepSpeed

### ISSUE THREAD

**Issue by afiaka87** [lucidrains/DALLE-pytorch#295]
Trying to run `generate.py` on a DeepSpeed checkpoint currently breaks. Using inference with DeepSpeed should be relatively simple I think - but I couldn't quite figure it out and realized most of the code I was writing actually just belonged in the the `DeepSpeedBackend` code which I hadn't yet grokked yet. Anyway; so I don't forget - here is some very very broken code bad code that I had written before giving up last night:

```python
n import deepspeed
import apex
from dalle_pytorch import distributed_utils
from dalle_pytorch.distributed_backends import DeepSpeedBackend
import argparse
from pathlib import Path
from tqdm import tqdm

# torch

import torch

from einops import repeat

# vision imports

from PIL import Image
from torchvision.utils import make_grid, save_image
from torchvision import transforms as T

# dalle related classes and utils

from dalle_pytorch import DiscreteVAE, OpenAIDiscreteVAE, VQGanVAE1024, DALLE
from dalle_pytorch.tokenizer import tokenizer, HugTokenizer, YttmTokenizer, ChineseTokenizer


DEEPSPEED_CP_AUX_FILENAME = 'auxiliary.pt'

# argument parsing

parser = argparse.ArgumentParser()

parser.add_argument('--dalle_path', type = str, required = True, help='path to your trained DALL-E') 
parser.add_argument('--text', type = str, required = True, help='your text prompt') 
parser.add_argument('--num_images', type = int, default = 128, required = False, help='number of images') 
parser.add_argument('--batch_size', type = int, default = 4, required = False, help='batch size') 
parser.add_argument('--top_k', type = float, default = 0.9, required = False, help='top k filter threshold') 
parser.add_argument('--outputs_dir', type = str, default = './outputs', required = False, help='output directory') 
parser.add_argument('--bpe_path', type = str, help='path to your huggingface BPE json file') 
parser.add_argument('--image_mask_path', type = str, help='Path to image to pass in as a mask during generation.') 
parser.add_argument('--hug', dest='hug', action = 'store_true') 
parser.add_argument('--chinese', dest='chinese', action = 'store_true') 
parser.add_argument('--taming', dest='taming', action='store_true') 

args = parser.parse_args()


def exists(val):
    return val is not None

# tokenizer

if exists(args.bpe_path):
    klass = HugTokenizer if args.hug else YttmTokenizer
    tokenizer = klass(args.bpe_path)
elif args.chinese:
    tokenizer = ChineseTokenizer()

# load DALL-E

dalle_path = Path('dalle-ds-cp')
loaded_obj = torch.load(str(dalle_path), map_location='cpu') 
dalle_params, vae_params, weights = loaded_obj['hparams'], loaded_obj['vae_params'], loaded_obj['weights']

vae = VQGanVAE1024()

dalle_params = dict(**dalle_params) 
image_size = vae.image_size

dalle = DALLE(vae = vae, **dalle_params).cuda() 
dalle.load_state_dict(weights)
distr_backend.check_batch_size(args.batch_size)
deepspeed_config = {
    'train_batch_size': args.batch_size,
    'amp': {
        'enabled': True,
        'opt_level': 'O1' 
    } 
}

dalle.load_checkpoint(dalle_path)
deepspeed.init_inference(dalle, checkpoint="./checkpoint.json", dtype=torch.float, replace_method='auto')

# generate images

texts = args.text.split('|')

for text in tqdm(texts):
    text = tokenizer.tokenize([args.text], dalle.text_seq_len).cuda()

    text = repeat(text, '() n -> b n', b = args.num_images)

    outputs = []

    for text_chunk in tqdm(text.split(args.batch_size), desc = f'generating images for - {text}'):
        output = dalle.generate_images(text_chunk, filter_thres = args.top_k)
        outputs.append(output)

    outputs = torch.cat(outputs)

    # save all images

    outputs_dir = Path(args.outputs_dir) / args.text.replace(' ', '_')[:(100)]
    outputs_dir.mkdir(parents = True, exist_ok = True)

    for i, image in tqdm(enumerate(outputs), desc = 'saving images'):
        save_image(image, outputs_dir / f'{i}.jpg', normalize=True)

    print(f'created {args.num_images} images at "{str(outputs_dir)}"')
```

**Comment by afiaka87** [comment]
Looking at `train_dalle.py` provides some insights from @janEbert prior grokking of Deep Speed. First mistake I'm making here is loading the checkpoint like this:

```sh
dalle.load_state_dict(weights)
```

which is apparently a no-no for DeepSpeed's engine.

**Comment by afiaka87** [comment]
Okay - I did things the way they're meant to be done (i believe) 

```

engine = deepspeed.init_inference(dalle, dtype=torch.half)
engine = deepspeed.init_inference(dalle, dtype=torch.half)
# training

# Saves a checkpoint before training begins to fail early when mis-configured.
# See https://github.com/lucidrains/DALLE-pytorch/wiki/DeepSpeed-Checkpoints
save_model(DALLE_OUTPUT_FILE_NAME)

for epoch in range(EPOCHS):
    if data_sampler:
        data_sampler.set_epoch(epoch)
    for i, (text, images) in enumerate(distr_dl):
        if i % 10 == 0 and distr_backend.is_root_worker():
            t = time.time()
        if args.fp16:
            images = images.half()
        text, images = map(lambda t: t.cuda(), (text, images))

        loss = engine(text, images, return_loss=True)
```

And this properly runs backpropagation via some automated strategy parameter I haven't understood yet. It's all undocumented so I'm just reading their code at this point. This may be an instance where their 'auto' policy is inserting values in the range of a -1,1 where the vqgan expects values in the range 0,1?

```sh
Traceback (most recent call last):
  File "DALLE-pytorch/train_dalle.py", line 456, in <module>
    loss = engine(text, images, return_loss=True)
  File "/mnt/evo_internal_1TB/.anaconda/envs/sparse/lib/python3.7/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/mnt/evo_internal_1TB/.anaconda/envs/sparse/lib/python3.7/site-packages/deepspeed/inference/engine.py", line 222, in forward
    return self.module(*inputs, **kwargs)
  File "/mnt/evo_internal_1TB/.anaconda/envs/sparse/lib/python3.7/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/mnt/evo_internal_1TB/DALLE-pytorch/dalle_pytorch/dalle_pytorch.py", line 486, in forward
    image = self.vae.get_codebook_indices(image)
  File "/mnt/evo_internal_1TB/.anaconda/envs/sparse/lib/python3.7/site-packages/torch/autograd/grad_mode.py", line 26, in decorate_context
    return func(*args, **kwargs)
  File "/mnt/evo_internal_1TB/DALLE-pytorch/dalle_pytorch/vae.py", line 173, in get_codebook_indices
    _, _, [_, _, indices] = self.model.encode(img)
  File "/mnt/evo_internal_1TB/.anaconda/envs/sparse/lib/python3.7/site-packages/taming_transformers-0.0.1-py3.7.egg/taming/models/vqgan.py", line 54, in encode
    quant, emb_loss, info = self.quantize(h)
  File "/mnt/evo_internal_1TB/.anaconda/envs/sparse/lib/python3.7/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/mnt/evo_internal_1TB/.anaconda/envs/sparse/lib/python3.7/site-packages/taming_transformers-0.0.1-py3.7.egg/taming/modules/vqvae/quantize.py", line 42, in forward
    torch.sum(self.embedding.weight**2, dim=1) - 2 * \
IndexError: Dimension out of range (expected to be in range of [-1, 0], but got 1)
```

**Comment by afiaka87** [comment]
As always, apologies to Jan who I'm sure has already explained this issue ;) I'll admit to some amount of laziness with regard to doing the due diligence on all this 🤷

**Comment by richcmwang** [comment]
generating seems to be tricky because it seems the deepspeed or DataParallel etc only work through an `nn.Module` (`forward`).  But the following code works for me to balance the gpus (model trained with stage 1) through dstr_dl:  

```
(distr_dalle, _, distr_dl, _) = distr_backend.distribute(
    args=args,
    model=dalle,
    optimizer=None,
    model_parameters=None,
    training_data=ds if using_deepspeed else dl,
    lr_scheduler=None,
    config_params=deepspeed_config,
)

for i, text in enumerate(distr_dl):
    t = time.time()
    text = text.cuda()
    print(f"generating {i} batch ...batch size {text.shape[0]}")
    image = dalle.generate_images(
        text, filter_thres=0.9)  # topk sampling at 0.9
    sec_per_sample = (time.time() - t) / BATCH_SIZE
    print(i, f'second_per_sample - {sec_per_sample}')

```
Note that I use `dalle` because `distr_dalle` does not work.  In my small test case (heads 16/depth 16),  both gpus loads are exactly the same.

**Comment by rom1504** [comment]
yeah I guess that's useful if you want to generate many sample. That doesn't help to improve the speed of one batch though

**Comment by richcmwang** [comment]
It does not improve the speed of one batch per GPU, but with 2 (or multiple) GPUs, it does improve the speed.  In my test case, the running time ratio for 1 GPU over 2 GPUs is 1.55.

**Comment by afiaka87** [comment]
Thanks @richcmwang! I'll work on this later unless you wanna make the PR. 

@rom1504 The DeepSpeed docs do indeed claim faster inference with the inference engine. Not sure how though.

**Comment by janEbert** [comment]
@richcmwang Exactly, they need the forward call which I'm pretty sure is also the reason why FP16 generation fails. They recommended using a simple if-switch in the `forward` method like `do_generations=True`. If it's given, don't do the normal forward calculations but just generations and exit. I didn't find the time until now to try it, though.

Aside from inference being parallelizable, I think the biggest benefit is being able to do inference with models that don't fit into memory.

**Comment by richcmwang** [comment]
@afiaka87  Please feel free to incorporate this.  I tried [inference](https://github.com/microsoft/DeepSpeed/blob/master/docs/_tutorials/inference-tutorial.md)  but either get incorrect key "checkpoint_path" or unknown type "DeepSpeed" error message.  Not sure the doc is accurate.
```
"checkpoint.json":
{
  "type": "DeepSpeed",
    "version": 0.3,
    "checkpoint_path": "path_to_checkpoints",
}
```
