### ISSUE TITLE
horovod and OpenAI's Pretrained VAE are incompatible.

### ISSUE THREAD

**Issue by wcshin-git** [lucidrains/DALLE-pytorch#330]
Hi! 
I think horovod and OpenAI's Pretrained VAE are incompatible.
When I ran `horovodrun -np 1 python train_dalle.py --image_text_folder path/to/data  --distributed_backend horovod`, but the following error occurred.
```
[0]<stderr>:Traceback (most recent call last):
[0]<stderr>:  File "train_dalle.py", line 482, in <module>
[0]<stderr>:    (distr_dalle, distr_opt, distr_dl, distr_scheduler) = distr_back[0]<stderr>:te(
[0]<stderr>:  File "/home/wcshin/DALLE-pytorch-forked/dalle_pytorch/distributed_[0]<stderr>:tributed_backend.py", line 145, in distribute
[0]<stderr>:    return self._distribute(
[0]<stderr>:  File "/home/wcshin/DALLE-pytorch-forked/dalle_pytorch/distributed_[0]<stderr>:ovod_backend.py", line 49, in _distribute
[0]<stderr>:    self.backend_module.broadcast_parameters(
[0]<stderr>:  File "/home/wcshin/anaconda3/envs/tmp_dalle/lib/python3.8/site-pac[0]<stderr>:d/torch/functions.py", line 53, in broadcast_parameters
[0]<stderr>:    handle = broadcast_async_(p, root_rank, name)
[0]<stderr>:  File "/home/wcshin/anaconda3/envs/tmp_dalle/lib/python3.8/site-pac[0]<stderr>:d/torch/mpi_ops.py", line 718, in broadcast_async_
[0]<stderr>:    return _broadcast_async(tensor, tensor, root_rank, name)
[0]<stderr>:  File "/home/wcshin/anaconda3/envs/tmp_dalle/lib/python3.8/site-pac[0]<stderr>:d/torch/mpi_ops.py", line 623, in _broadcast_async
[0]<stderr>:    function = _check_function(_broadcast_function_factory, tensor)
[0]<stderr>:  File "/home/wcshin/anaconda3/envs/tmp_dalle/lib/python3.8/site-pac[0]<stderr>:d/torch/mpi_ops.py", line 87, in _check_function
[0]<stderr>:    raise ValueError('Tensor is required to be contiguous.')
[0]<stderr>:ValueError: Tensor is required to be contiguous.
```

Thank you!

**Comment by wcshin-git** [comment]
@janEbert

**Comment by johngore123** [comment]
I tried using 4 tesla v100's and it worked even with OpenAI's Pretrained VAE

**Comment by wcshin-git** [comment]
Oh, really? I'm using RTX 3090 and when I try to use horovod with OpenAidVAE, I get an error like that...

**Comment by johngore123** [comment]
> Oh, really? I'm using RTX 3090 and when I try to use horovod with OpenAidVAE, I get an error like that...

Horovod seems to works best using multi-gpus, but it should still work on 1 so that might be an version error or something. error seems to hint at mpi begin the problem. so you may have an incompatible version.

**Comment by johngore123** [comment]
Does horovod work with taming for you?

**Comment by wcshin-git** [comment]
Yes, horovod work with taming when I ran `horovodrun -np 1 python train_dalle.py --image_text_folder path/to/data --taming --distributed_backend horovod`.
Even OpenAI's dVAE works when I don't use horovod.

**Comment by janEbert** [comment]
Hey, thanks for the ping! I was able to reproduce the error and #338 should fix this. Hope it helps.
