### ISSUE TITLE
RuntimeError: Expected object of scalar type Half but got scalar type Float for argument #2 'mat2' in call to _th_bmm_out

### ISSUE THREAD

**Issue by Gitsamshi** [lucidrains/DALLE-pytorch#333]
Have the error when running --amp:  deepspeed train_dalle.py --image_text_folder /home/18zs11/dataset/cub/image-and-text --taming --bpe_path ./bpe.model --distr_backend deepspeed --amp;  Does anyone have the same error?

[2021-07-06 22:13:06,616] [INFO] [logging.py:68:log_dist] [Rank 0] Saving model checkpoint: cub/dalle_cub-ds-cp/global_step0/mp_rank_00_model_states.pt       
/home/18zs11/DALLE-pytorch/dalle_pytorch/tokenizer.py:263: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach$
) or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).                                                              
  result[i, :len(tokens)] = torch.tensor(tokens)                                                                                                              
/home/18zs11/DALLE-pytorch/dalle_pytorch/tokenizer.py:263: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach$
) or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).                                                              
  result[i, :len(tokens)] = torch.tensor(tokens)                                                                                                              
Traceback (most recent call last):                                                                                                                            
  File "train_dalle.py", line 562, in <module>                                                                                                                
    loss = distr_dalle(text, images, return_loss=True)                                                                                                        
  File "/home/18zs11/anaconda3/envs/clip/lib/python3.7/site-packages/torch/nn/modules/module.py", line 727, in _call_impl                                     
    result = self.forward(*input, **kwargs)
  File "/home/18zs11/anaconda3/envs/clip/lib/python3.7/site-packages/deepspeed/runtime/engine.py", line 1102, in forward
    loss = self.module(*inputs, **kwargs)
  
File "/home/18zs11/anaconda3/envs/clip/lib/python3.7/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/18zs11/DALLE-pytorch/dalle_pytorch/dalle_pytorch.py", line 485, in forward
    image = self.vae.get_codebook_indices(image)
  File "/home/18zs11/anaconda3/envs/clip/lib/python3.7/site-packages/torch/autograd/grad_mode.py", line 26, in decorate_context
    return func(*args, **kwargs)
  File "/home/18zs11/DALLE-pytorch/dalle_pytorch/vae.py", line 196, in get_codebook_indices
    _, _, [_, _, indices] = self.model.encode(img)
  File "/home/18zs11/anaconda3/envs/clip/lib/python3.7/site-packages/taming/models/vqgan.py", line 58, in encode
    quant, emb_loss, info = self.quantize(h)
  File "/home/18zs11/anaconda3/envs/clip/lib/python3.7/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/18zs11/anaconda3/envs/clip/lib/python3.7/site-packages/taming/modules/vqvae/quantize.py", line 282, in forward
    torch.einsum('bd,dn->bn', z_flattened, rearrange(self.embedding.weight, 'n d -> d n'))
  File "/home/18zs11/anaconda3/envs/clip/lib/python3.7/site-packages/torch/functional.py", line 344, in einsum
    return _VF.einsum(equation, operands)  # type: ignore
RuntimeError: Expected object of scalar type Half but got scalar type Float for argument #2 'mat2' in call to _th_bmm_out

**Comment by lucidrains** [comment]
@rom1504 is this possibly related to the new VQVAE model?

**Comment by rom1504** [comment]
yes very likely but I don't know what would be the fix here. Maybe trying `self.model.encode(img.half())` could help
All the changes they made are happening in that commit https://github.com/CompVis/taming-transformers/commit/04c8ad6c0fa4650e3d600faee793515c4aa2658c

**Comment by Gitsamshi** [comment]
Thanks for the suggestion, but using self.model.encode(img.half()) still doesn't work.

**Comment by Gitsamshi** [comment]
settled, just change the eisum ops in the taming transformer.

**Comment by rom1504** [comment]
do you have more details about that? (so other people can do the same thing)

**Comment by Gitsamshi** [comment]
Sure, glad to do that. change line 282 https://github.com/CompVis/taming-transformers/blob/master/taming/modules/vqvae/quantize.py 
torch.einsum('bd,dn->bn', z_flattened.float(), rearrange(self.embedding.weight.float(), 'n d -> d n')) --> torch.matmul(z_flattened, self.embedding.weight.t())

**Comment by NomanTrips** [comment]
I had this issue too when trying to do apex mixed precision with deepspeed. The change suggested by @Gitsamshi worked for me.
