### ISSUE TITLE
AttributeError: module 'triton' has no attribute 'kernel'

### ISSUE THREAD

**Issue by jayralencar** [lucidrains/DALLE-pytorch#342]
Hi,

When executing the [Dall-E Generation notebook](https://colab.research.google.com/drive/1b8va5g852hq3p7yro7xWY3Cc-bd2CRdv#scrollTo=682c5804-5f97-469f-8cf1-1cc8356591b8) in Colab I am getting this error:

```2021-07-28 19:51:49.943663: I tensorflow/stream_executor/platform/default/dso_loader.cc:53] Successfully opened dynamic library libcudart.so.11.0
Working with z of shape (1, 256, 16, 16) = 65536 dimensions.
Downloading: "https://download.pytorch.org/models/vgg16-397923af.pth" to /root/.cache/torch/hub/checkpoints/vgg16-397923af.pth
100% 528M/528M [00:03<00:00, 181MB/s]
Downloading vgg_lpips model from https://heibox.uni-heidelberg.de/f/607503859c864bc1b30b/?dl=1 to taming/modules/autoencoder/lpips/vgg.pth
8.19kB [00:00, 73.1kB/s]                
loaded pretrained LPIPS loss from taming/modules/autoencoder/lpips/vgg.pth
VQLPIPSWithDiscriminator running with hinge loss.
Loaded VQGAN from /root/.cache/dalle/vqgan.1024.model.ckpt and /root/.cache/dalle/vqgan.1024.config.yml
0it [00:00, ?it/s]
generating images for - the grand canyon with snow on it:   0% 0/1 [00:00<?, ?it/s]/usr/local/lib/python3.7/dist-packages/torch/_tensor.py:575: UserWarning: floor_divide is deprecated, and will be removed in a future version of pytorch. It currently rounds toward 0 (like the 'trunc' function NOT 'floor'). This results in incorrect rounding for negative values.
To keep the current behavior, use torch.div(a, b, rounding_mode='trunc'), or for actual floor division, use torch.div(a, b, rounding_mode='floor'). (Triggered internally at  /pytorch/aten/src/ATen/native/BinaryOps.cpp:467.)
  return torch.floor_divide(self, other)
generating images for - the grand canyon with snow on it:   0% 0/1 [00:00<?, ?it/s]
0it [00:00, ?it/s]
Traceback (most recent call last):
  File "/content/DALLE-pytorch/generate.py", line 116, in <module>
    output = dalle.generate_images(text_chunk, filter_thres = args.top_k)
  File "/usr/local/lib/python3.7/dist-packages/torch/autograd/grad_mode.py", line 28, in decorate_context
    return func(*args, **kwargs)
  File "/content/DALLE-pytorch/dalle_pytorch/dalle_pytorch.py", line 42, in inner
    out = fn(model, *args, **kwargs)
  File "/content/DALLE-pytorch/dalle_pytorch/dalle_pytorch.py", line 480, in generate_images
    logits = self(text, image, mask = mask)[:, -1, :]
  File "/usr/local/lib/python3.7/dist-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "/content/DALLE-pytorch/dalle_pytorch/dalle_pytorch.py", line 552, in forward
    out = self.transformer(tokens)
  File "/usr/local/lib/python3.7/dist-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "/content/DALLE-pytorch/dalle_pytorch/transformer.py", line 142, in forward
    return self.layers(x, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "/content/DALLE-pytorch/dalle_pytorch/reversible.py", line 156, in forward
    out =  _ReversibleFunction.apply(x, blocks, args)
  File "/content/DALLE-pytorch/dalle_pytorch/reversible.py", line 113, in forward
    x = block(x, **kwarg)
  File "/usr/local/lib/python3.7/dist-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "/content/DALLE-pytorch/dalle_pytorch/reversible.py", line 65, in forward
    y1 = x1 + self.f(x2, record_rng=self.training, **f_args)
  File "/usr/local/lib/python3.7/dist-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "/content/DALLE-pytorch/dalle_pytorch/reversible.py", line 40, in forward
    return self.net(*args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "/content/DALLE-pytorch/dalle_pytorch/transformer.py", line 53, in forward
    return self.fn(x, **kwargs) * self.scale
  File "/usr/local/lib/python3.7/dist-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "/content/DALLE-pytorch/dalle_pytorch/transformer.py", line 62, in forward
    return self.fn(self.norm(x), **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "/content/DALLE-pytorch/dalle_pytorch/attention.py", line 362, in forward
    out = self.attn_fn(q, k, v, attn_mask = attn_mask, key_padding_mask = key_pad_mask)
  File "/usr/local/lib/python3.7/dist-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/deepspeed/ops/sparse_attention/sparse_self_attention.py", line 152, in forward
    attn_output_weights = sparse_dot_sdd_nt(query, key)
  File "/usr/local/lib/python3.7/dist-packages/deepspeed/ops/sparse_attention/matmul.py", line 745, in __call__
    time_db)
  File "/usr/local/lib/python3.7/dist-packages/deepspeed/ops/sparse_attention/matmul.py", line 549, in forward
    c_time)
  File "/usr/local/lib/python3.7/dist-packages/deepspeed/ops/sparse_attention/matmul.py", line 188, in _sdd_matmul
    _sparse_matmul.sdd_cache[key] = triton.kernel(
AttributeError: module 'triton' has no attribute 'kernel'
Finished generating images, attempting to display results...
<Figure size 2304x2304 with 0 Axes>
<Figure size 4608x4608 with 0 Axes>```

**Comment by lucidrains** [comment]
@jayralencar Hey Jayr! I think that's related to Triton releasing 1.0 today

If you were to downgrade to anything less than 1.0, it should work!

**Comment by lucidrains** [comment]
will put out a fix later!

**Comment by jayralencar** [comment]
Thanks, @lucidrains 

I downgraded to 0.4.2 and it worked.

**Comment by lucidrains** [comment]
updated the readme!
