### ISSUE TITLE
Error when using custom tokenizer. happens on the newest version too.

### ISSUE THREAD

**Issue by js12312** [lucidrains/DALLE-pytorch#353]
C:\Users\valte\Documents\DALLE-pytorch-0.13.2\dalle_pytorch\tokenizer.py:263: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  result[i, :len(tokens)] = torch.tensor(tokens)
0 0 loss - 9.183201789855957
Traceback (most recent call last):
  File "train_dalle.py", line 587, in <module>
    decoded_text = tokenizer.decode(token_list)
  File "C:\Users\valte\Documents\DALLE-pytorch-0.13.2\dalle_pytorch\tokenizer.py", line 244, in decode
    return self.tokenizer.decode(tokens, ignore_ids = [0])
TypeError: decode() got an unexpected keyword argument 'ignore_ids'

**Comment by ShuaiWang97** [comment]
> union type operation

Hi, I also face the same error. I changed def decode(self, tokens, pad_tokens = {}): to def decode(self, tokens, pad_tokens = set()): according to https://stackoverflow.com/questions/21651745/dict-object-has-no-attribute-union. Not sure it is fully right but it is running now.
