### ISSUE TITLE
Invalid PTX code

### ISSUE THREAD

**Issue by hamdjalil** [lucidrains/DALLE-pytorch#378]
**getting this error on the colab ** 

It appears that Triton produced invalid PTX code:
generating images for - a female mannequin dressed in an olive button-down shirt and gold palazzo pants:   0% 0/3 [00:02<?, ?it/s]
0it [00:02, ?it/s]
Traceback (most recent call last):
  File "/content/DALLE-pytorch/generate.py", line 117, in <module>
    output = dalle.generate_images(text_chunk, filter_thres = args.top_k)
  File "/usr/local/lib/python3.7/dist-packages/torch/autograd/grad_mode.py", line 28, in decorate_context
    return func(*args, **kwargs)
  File "/content/DALLE-pytorch/dalle_pytorch/dalle_pytorch.py", line 43, in inner
    out = fn(model, *args, **kwargs)
  File "/content/DALLE-pytorch/dalle_pytorch/dalle_pytorch.py", line 488, in generate_images
    logits = self(text, image, mask = mask)[:, -1, :]
  File "/usr/local/lib/python3.7/dist-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "/content/DALLE-pytorch/dalle_pytorch/dalle_pytorch.py", line 560, in forward
    out = self.transformer(tokens)
  File "/usr/local/lib/python3.7/dist-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "/content/DALLE-pytorch/dalle_pytorch/transformer.py", line 231, in forward
    return self.layers(x, rotary_pos_emb = self.pos_emb, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "/content/DALLE-pytorch/dalle_pytorch/reversible.py", line 139, in forward
    x = x + f(x, **f_args)
  File "/usr/local/lib/python3.7/dist-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "/content/DALLE-pytorch/dalle_pytorch/transformer.py", line 54, in forward
    return self.fn(x, **kwargs) * self.scale
  File "/usr/local/lib/python3.7/dist-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "/content/DALLE-pytorch/dalle_pytorch/transformer.py", line 67, in forward
    x = self.fn(x, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "/content/DALLE-pytorch/dalle_pytorch/attention.py", line 381, in forward
    out = self.attn_fn(q, k, v, attn_mask = attn_mask, key_padding_mask = key_pad_mask)
  File "/usr/local/lib/python3.7/dist-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/deepspeed/ops/sparse_attention/sparse_self_attention.py", line 152, in forward
    attn_output_weights = sparse_dot_sdd_nt(query, key)
  File "/usr/local/lib/python3.7/dist-packages/deepspeed/ops/sparse_attention/matmul.py", line 745, in __call__
    time_db)
  File "/usr/local/lib/python3.7/dist-packages/deepspeed/ops/sparse_attention/matmul.py", line 549, in forward
    c_time)
  File "/usr/local/lib/python3.7/dist-packages/deepspeed/ops/sparse_attention/matmul.py", line 224, in _sdd_matmul
    grid=lambda opt: [opt.TZ,
  File "/usr/local/lib/python3.7/dist-packages/triton/kernel.py", line 116, in __call__
    kernel = self.fn.autotune(params, grid, self.stream)
RuntimeError: CUDA: Error- invalid ptx

**Comment by chqwer2** [comment]
Hi, I have installed 0.4.2 version, but got Error as followed:

No module named 'triton.language'

Do you guys get the same problem?
