### ISSUE TITLE
Tensor device error when computing kl_div in VAE

### ISSUE THREAD

**Issue by kobiso** [lucidrains/DALLE-pytorch#41]
Hello, @lucidrains  :)

I saw https://github.com/lucidrains/DALLE-pytorch/commit/706f06db0c8cede9fe02d16cbfe8ee09144858ea this commit, and I got below error when I trained with it.

```bash
Traceback (most recent call last):
  File "/root/.pycharm_helpers/pydev/pydevd.py", line 1434, in _exec
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "/root/.pycharm_helpers/pydev/_pydev_imps/_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "/home/shared/workspace/torch_research/text-to-image/dalle-pytorch/train_VAE.py", line 237, in <module>
    main()
  File "/home/shared/workspace/torch_research/text-to-image/dalle-pytorch/train_VAE.py", line 164, in main
    loss = get_loss(images)
  File "/home/shared/workspace/torch_research/text-to-image/dalle-pytorch/train_VAE.py", line 145, in get_loss
    loss = F.smooth_l1_loss(images, recons) + vae(images, return_loss=True)
  File "/opt/conda/lib/python3.7/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/shared/workspace/torch_research/text-to-image/dalle-pytorch/models/model_arch.py", line 173, in forward
    kl_div = (qy * (log_qy - g)).sum(dim = (1, 2)).mean()
RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cpu!
```

Reason is the device of `g` construction is not adaptable to the current device.

https://github.com/lucidrains/DALLE-pytorch/blob/706f06db0c8cede9fe02d16cbfe8ee09144858ea/dalle_pytorch/dalle_pytorch.py#L172

This can be solved by
```python
device = img.device
....
g = torch.log(torch.tensor([1. / num_tokens], device=device))
```

Please check if it is a correct way to fix :)

**Comment by lucidrains** [comment]
@kobiso oh oops! introduced it by accident lol :pray: https://github.com/lucidrains/DALLE-pytorch/commit/c02aaf834f504d1a1a8165bc439f868eb376433d

**Comment by kobiso** [comment]
Thanks for quick revision!

**Comment by johnmccain** [comment]
It appears that this fix (c02aaf8) does not work (at least with torch==1.7.1 on Windows). 

```python
import torch
from torch import nn
from dalle_pytorch import DiscreteVAE

device = torch.device('cuda:0')
vae = DiscreteVAE(image_size=256, num_tokens=512, codebook_dim=512, num_layers=3).to(device)

input_img = torch.rand(1, 3, 256, 256).to(device)
loss = vae(input_img, return_loss=True)
```

```
Traceback (most recent call last):
  File "minimal_legacyerror.py", line 9, in <module>
    loss = vae(input_img, return_loss=True)
  File "C:\Users\johnm\Documents\projects\text-to-image\venv\lib\site-packages\torch\nn\modules\module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "C:\Users\johnm\Documents\projects\text-to-image\venv\lib\site-packages\dalle_pytorch\dalle_pytorch.py", line 172, in forward
    g = torch.log(torch.Tensor([1. / num_tokens], device = device))
RuntimeError: legacy constructor for device type: cpu was passed device type: cuda, but device type must be: cpu
```

Changing 
```python
g = torch.log(torch.Tensor([1. / num_tokens], device = device))
```
to 
```python
g = torch.log(torch.Tensor([1. / num_tokens], device = device))
```
fixes the problem.

**Comment by kobiso** [comment]
@johnmccain you are right,
I meant to fix it how you suggested in https://github.com/lucidrains/DALLE-pytorch/issues/41#issue-809268592 .
(Specifically, `torch.Tensor` -> `torch.tensor`)
I guess there were mistake in https://github.com/lucidrains/DALLE-pytorch/commit/c02aaf834f504d1a1a8165bc439f868eb376433d
@lucidrains please check it :)

**Comment by lucidrains** [comment]
@johnmccain @kobiso i did correct it in the latest version! https://github.com/lucidrains/DALLE-pytorch/blob/main/dalle_pytorch/dalle_pytorch.py#L172 let me push out another patch just in case
