### ISSUE TITLE
pkg_resources

### ISSUE THREAD

**Issue by Holmes2002** [lucidrains/DALLE-pytorch#430]
PS C:\Users\user\Documents\Holmes\Paper with code> cd .\DALLE-pytorch\
PS C:\Users\user\Documents\Holmes\Paper with code\DALLE-pytorch> python train_vae.py --image_folder mscoco_img
2022-05-29 07:51:16.566099: I tensorflow/stream_executor/platform/default/dso_loader.cc:53] Successfully opened dynamic library cudart64_110.dll
C:\Users\user\AppData\Local\Programs\Python\Python39\lib\site-packages\setuptools\distutils_patch.py:25: UserWarning: Distutils was imported before Setuptools. This usage is discouraged and may exhibit undesirable behaviors or errors. Please use Setuptools' objects directly or at least import Setuptools first.
  warnings.warn(
Traceback (most recent call last):
  File "C:\Users\user\Documents\Holmes\Paper with code\DALLE-pytorch\train_vae.py", line 21, in <module>
    from dalle_pytorch import distributed_utils
  File "C:\Users\user\Documents\Holmes\Paper with code\DALLE-pytorch\dalle_pytorch\__init__.py", line 5, in <module>
    __version__ = get_distribution('dalle_pytorch').version
  File "C:\Users\user\AppData\Local\Programs\Python\Python39\lib\site-packages\pkg_resources\__init__.py", line 480, in get_distribution
    dist = get_provider(dist)
  File "C:\Users\user\AppData\Local\Programs\Python\Python39\lib\site-packages\pkg_resources\__init__.py", line 356, in get_provider
    return working_set.find(moduleOrReq) or require(str(moduleOrReq))[0]
  File "C:\Users\user\AppData\Local\Programs\Python\Python39\lib\site-packages\pkg_resources\__init__.py", line 899, in require
    needed = self.resolve(parse_requirements(requirements))
  File "C:\Users\user\AppData\Local\Programs\Python\Python39\lib\site-packages\pkg_resources\__init__.py", line 785, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'dalle_pytorch' distribution was not found and is required by the application

Why i run in python3.7 and 3.9 have same issues?

**Comment by lucidrains** [comment]
@Holmes2002 oh yes, you must have not installed the package from pip

do you want to try 1.6.3 and see if it resolves your issue? or just `git pull` to get the latest changes
